name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  extension_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -v test "*test*.py"

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - name: Upload Windows executable file
        uses: actions/upload-artifact@v1
        with:
          name: esp-idf-extension.vsix
          path: esp-idf-extension.vsix